### ISSUE TITLE
[BUG] issue with mrgn in overlay.css

### ISSUE THREAD

**Issue by DMcDona** [ServiceCanada/invitation-manager#5]
**Summary**
Line 103 in [overlay.css](https://github.com/ServiceCanada/invitation-manager/blob/master/src/Overlay.css) sets margin for all sides instead of just the top, as mrgn-tp-md class would suggest. This causes mrgn-tp-md to break across the site.

Current:
`.mrgn-tp-md  { 
	margin: 5px; 
}`
Expected:
`.mrgn-tp-md  { 
	margin-top: 5px; 
}`

**Steps to reproduce the behavior:**
1. Include Overlay.css
2. Use mrgn-tp-md expecting to only add a margin to the top of element
3. See mrgn-tp-md has instead added a 5px margin on all sides.

**Expected behavior**
mrgn-tp-md to only effect the top margin

I can submit a pull request if preferred, but unsure if this originated from a typo or a workaround for another issue.

Thanks!

**Comment by GormFrank** [comment]
Thank you @DMcDona for bringing this up.

@polmih Can you tackle this whenever you have the chance? And please try to encapsulate the class in either `.gc-im-modal-body` or wherever the `.mrgn-tp-md` class is used specific to the **Invitation Manager** so that it doesn't conflict with **WET-BOEW** if a single website uses both **WET-BOEW** and the **Invitation Manager**? Thanks!

**Comment by markwooff** [comment]
It would agree that the following CSS rules need to be more specific since they'd clash with WET-BOEW stylesheets:

```
.list-inline {
	padding-left: 0;
	list-style: none;
}
					
.mrgn-tp-md  { 
	margin: 5px; 
}
```

**Comment by DMcDona** [comment]
Thank you all!
